services:

  json-server:
    build:
      context: ./frontend/server

    container_name: json-server

    ports:
      - "3001:3001"

    restart: unless-stopped

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile

    container_name: nginx

    depends_on:
      - json-server

    ports:
      - "80:80"

    restart: unless-stopped